# Temporarily use legacy infrastructure until Travis resolves MySQL issues with their containerized infrastructure.
# @see https://github.com/travis-ci/travis-ci/issues/6842
sudo: required
language: php
dist: trusty

php:
  - 5.6
  - 7.1

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  matrix:
    - RELEASE=stable COMPOSER_CHANNEL=stable
    # - RELEASE=dev COMPOSER_CHANNEL=stable
    # - RELEASE=stable COMPOSER_CHANNEL=snapshot

before_install:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version

install:
  # Create MySQL Database.
  - mysql -e 'create database drupalcz;'

  # Set up Apache.
  - sudo a2enmod rewrite actions fastcgi alias
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - if [[ -f ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ]] ; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf ; fi
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "variables_order = "EGPCS"" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Configure apache virtual hosts.
  - sudo cp -f tests/build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default

  # Restart the server.
  - sudo service apache2 restart
  - cat /etc/apache2/sites-available/default

  # Install stable Drush 8.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --prefer-dist --no-interaction drush/drush:^8.1

  # Disable sendmail.
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Set up site.
  - composer --verbose install
  - cd ./docroot
  - ./../vendor/bin/drush si dcz install_configure_form.update_status_module='array(FALSE,FALSE)' --sites-subdir=default --verbose --account-name=admin --account-pass=admin --site-mail=drupalcz_travis_dev@klaska.net --site-name="Drupal.cz" --yes
  - cd ..

  # Set up and run migrations.
  - mysql -e 'create database d6migratesource;'
  - git clone https://github.com/Drupalcz/drupalcz_db.git
  - mysql -uroot d6migratesource < ./drupalcz_db/dcz_scrubbed_slim.sql
  - cd ./docroot
  - ./../vendor/bin/drush cim -y
  - ./../vendor/bin/drush cr
  - ./../vendor/bin/drush en -y dcz_migrate
  - ./../vendor/bin/drush migrate-status
  #- ./../vendor/bin/drush migrate-import --group=dcz6 -vvv
  - ./../vendor/bin/drush migrate-status
  - ./../vendor/bin/drush cr
  - cd ..

  # Setup behat.
  - cd ./tests/behat
  - composer install --prefer-dist --no-interaction
  - cd ../..

  # Setup display for selenium.
  - sh -e /etc/init.d/xvfb start

  # Get Selenium.
  - if [[ ! -e "$HOME/custom/selenium-server-standalone-2.44.0.jar" ]]; then wget --directory-prefix="$HOME/custom" http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar; fi;
  - java -jar $HOME/custom/selenium-server-standalone-2.44.0.jar -p 4444 > /dev/null 2>&1 &

script:
  - if [[ $RELEASE = dev ]]; then composer --verbose remove --no-update drupal/console; fi;
  - if [[ $RELEASE = dev ]]; then composer --verbose require --no-update drupal/core:8.4.x-dev drush/drush:9.0.x-dev; fi;
  - if [[ $RELEASE = dev ]]; then composer --verbose update; fi;
  - cd $TRAVIS_BUILD_DIR/docroot
  - ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
  - ./../vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
  - until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because docroot/ has no composer.json
  # Ignore PageCache group temporarily, @see https://www.drupal.org/node/2770673
  - ./../vendor/bin/phpunit -c core --testsuite unit --exclude-group Composer,DependencyInjection,PageCache
  - ./../vendor/bin/drush
  - if [[ $RELEASE = stable ]]; then ./../vendor/bin/drupal; fi;
