dev:
  host: ded-2299.prod.hosting.acquia.com
  options:
    ac-env: prod
    ac-realm: prod
    ac-site: drupalcz
  paths:
    drush-script: drush8
  root: /var/www/html/drupalcz.prod/docroot
  uri: drupalcz.prod.acquia-sites.com
  user: drupalcz.prod
livedev:
  options:
    parent: '@drupalcz.prod'
  root: /mnt/gfs/drupalcz.prod/livedev/docroot
