favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://drupalczd8.local/themes/custom/drupalcz_skin/favicon.ico'
  use_default: 1
schema: '8000'
features:
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: 1
breadcrumb_home: 1
navbar_position: fixed-top
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
