definitions:
  user__page:
    weight: -50
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
  user__logout:
    weight: -48
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
